server:
  port: 8888
  
spring:
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/loganmca/cloudconfig.git
          addLabelLocations: false
          searchPaths: /config/app/coonfigurations
          #basedir: \config\app\coonfigurations\
          cloneOnStart: true
